-- Add event page content fields
ALTER TABLE events ADD COLUMN IF NOT EXISTS cover_photo_url TEXT DEFAULT NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS welcome_message TEXT DEFAULT NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS schedule JSONB DEFAULT NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS menu JSONB DEFAULT NULL;
